import test from 'node:test';
import assert from 'node:assert/strict';
import { scryptSync } from 'node:crypto';
import { createApp } from './server.mjs';
const salt = '0123456789abcdef0123456789abcdef';
const password = 'test-only-password';
await test('authentication, statistics, privacy, logout and throttling', async t => {
  const app = await createApp({dbPath: ':memory:', secret: 'a'.repeat(64), passwordHash: `${salt}:${scryptSync(password, salt, 64).toString('hex')}`});
  await new Promise(resolve => app.listen(0, '127.0.0.1', resolve));
  t.after(() => new Promise(resolve => app.close(resolve)));
  const base = `http://127.0.0.1:${app.address().port}`;
  const request = (path, data, headers = {}) => fetch(base + path, {method: data ? 'POST' : 'GET', headers: {'Content-Type':'application/json', Origin:'https://duckdisk.com', 'User-Agent':'Mozilla/5.0 Macintosh Safari/605.1', ...headers}, ...(data ? {body: JSON.stringify(data)} : {})});
  assert.equal((await request('/api/admin/visits')).status, 401);
  assert.equal((await request('/api/auth/login', {email:'admin@duckdisk.com',password:'wrong'})).status,401);
  assert.equal((await request('/api/auth/login', {email:'admin@duckdisk.com',password}, {Origin:'https://evil.test'})).status,403);
  const login = await request('/api/auth/login', {email:'admin@duckdisk.com',password});
  assert.equal(login.status,200);
  const setCookie = login.headers.get('set-cookie');
  assert.match(setCookie,/HttpOnly; Secure; SameSite=Strict/);
  const Cookie = setCookie.split(';')[0];
  assert.equal((await request('/api/admin/visits?days=10000',null,{Cookie})).status,400);
  const visit = {page:'/',referrer:'https://example.com/private?secret=removed',language:'en'};
  for(let i=0;i<2;i++) assert.equal((await (await request('/api/visits/track',visit,{'X-Real-IP':'8.8.8.8'})).json()).tracked,true);
  await request('/api/visits/track',visit,{'X-Real-IP':'8.8.8.8','CF-Connecting-IP':'1.1.1.1'});
  assert.equal((await (await request('/api/visits/track',visit,{DNT:'1'})).json()).tracked,false);
  assert.equal((await request('/api/visits/track',{page:'/admin/'})).status,400);
  assert.equal((await request('/api/visits/track',{page:'/?token=secret'})).status,400);
  const data = await (await request('/api/admin/visits?days=7&limit=1',null,{Cookie})).json();
  assert.equal(data.summary.pageviews,3);
  assert.equal(data.summary.visits,1);
  assert.equal(data.events.length,1);
  assert.equal(data.events[0].ip,'8.8.8.0');
  assert.equal(data.events[0].referrer,'https://example.com');
  assert.equal(data.locations[0].pageviews,3);
  await request('/api/auth/logout',{}, {Cookie});
  assert.equal((await request('/api/admin/visits',null,{Cookie})).status,401);
  for(let i=0;i<10;i++) await request('/api/auth/login',{email:'admin@duckdisk.com',password:'wrong'},{'X-Real-IP':'1.2.3.4'});
  assert.equal((await request('/api/auth/login',{email:'admin@duckdisk.com',password},{'X-Real-IP':'1.2.3.4'})).status,429);
});
